src/lib/components/UnloadEventHandler.tsx
src/lib/services/assistanceService.ts

SELC-144 tracking mailto event

Selc 144 track events

---

README.md
src/lib/hooks/useReduxCachedValue.tsx

useReduxCachedValueTranscoded transcode function will accept retrieverServiceArgs

---

CODEOWNERS
package.json
src/lib/components/Header/Header.tsx
yarn.lock

+ code owners: correct "leremedda" to "loremedda", added "kaiban".

SELC-1407 using new enableAssistance prop in header

---

src/lib/utils/utils.ts

added new characters acceptes
character accepted during CF validation: aeiouàèìòùé'üöäẅæâçêîôœûščžẞ-

SELC-2552-added-new-characters-acceptes

---

src/lib/components/SessionModal.tsx

CSS changes
Changes to make the sessionModal component used for popups in the selfcare or pnpg portals.

PNPG-196 Responsive mobile SessionModal component

---

src/lib/components/SessionModal.tsx

Added CSS FlexWrap for show button in reverse when the window shrink down

PNPG-196 Added CSS FlexWrap for show button in reverse when the window shrink down

---

src/lib/components/Footer/Footer.tsx
src/lib/config/env.ts

- Added two new optional props to Footer component: privacyPolicy, termsAndConditions in order to assign dynamically the wanted privacy and policy, terms and conditions 
- Changed the certifications and information security links
-  Change request and adopted this solution for have the possibility to easily assign these two links in the future as well
-  Changed the certifications and information security links

PNPG-200 PNPG-201

---

src/lib/components/Footer/Footer.tsx

Updated footer post login pointer links privacy, terms and conditions

Updated footer post login pointer links privacy + terms and conditions

---

package.json
src/lib/components/Footer/Footer.tsx
src/lib/components/Footer/FooterConfig.tsx
yarn.lock

Added languages: english, french, german, slovenian
In order to translate the entire portal, the languages: English, German, French and Slovenian have been added to the switch in the footer

SELC-2582 Added languages: english, french, german, slovenian

---

src/lib/locale/de.ts
src/lib/locale/en.ts
src/lib/locale/fr.ts
src/lib/locale/locale-utils.ts
src/lib/locale/sl.ts

Destructure all new language in order to make it work properly the change language trigger
The trigger for change languages in footer doesn't work because the language aren't destructured after this implementation. With this implementation, work all properly

SELC-2582 Destructure all new language in order to make it work properly the change language trigger

---

src/lib/locale/en.ts
src/lib/locale/it.ts

Fixed two typos present in the english translation json
Fixed two typos present in the english translation json keys which did not match what was in the code

Fixed two typos present in the english translation json

---

.env.development.local
package.json
src/lib/components/Footer/Footer.tsx
src/lib/config/env.ts
yarn.lock

Used a environment variable to manage correct links in the footer based to product and actual environment
Optimized the code by using an environment variable for automatically manage correct links

Used a environment variable to manage correct links in the footer based to product and actual environment

---

package.json
yarn.lock

SELC-2590 - update common

---

src/lib/components/Footer/Footer.tsx
src/lib/locale/de.ts
src/lib/locale/fr.ts
src/lib/locale/sl.ts

Fixed bad localized string
Translation for this element now work correctly

Fixed bad localized string

---

src/lib/components/Footer/Footer.tsx
src/lib/config/env.ts
src/lib/locale/it.ts

SELC-3056 change label of footer link from Model 321 to Model 231
Change label as requested.
Run application locally. Click on the Model 231 link in footer pre-login

SELC-3056 change model 321 to Model 231 in footer link

---

src/lib/components/Footer/Footer.tsx
src/lib/config/env.ts
src/lib/locale/it.ts

Added "accessibility" voice in the footer (for logged and not-logged)
Following the accessibility declaration of the SelfCare portal, it was necessary to add the item with the related link to the accessibility declaration
Graphic test (both in the case of a logged in and non logged in user) and proof of correct redirect

SELC-3090 Added "accessibility" voice in the footer (for logged and not-logged)

---

src/lib/config/env.ts
src/lib/utils/constants.ts

Added regexp email and rename environment var following the changes made on azure
Optimization added in order to import the regexp in the various points where it is used, the renaming of the environment variables serves, however, to make the redirects work correctly in the two footer entries

Added regexp email + rename vars

---

src/lib/components/Header/Header.tsx

…utton
SELC-3135 add onDocumentationClick prop to toggle visibility of doc button
In the header in some parts of the application should be a documentation  button should be visible to link to gitbook.
Tested locally

SELC-3135 add onDocumentationClick prop to toggle visibility of documentation button

---

src/lib/components/Footer/Footer.tsx
src/lib/locale/de.ts
src/lib/locale/en.ts
src/lib/locale/fr.ts
src/lib/locale/it.ts
src/lib/locale/sl.ts

Updated translations
In order to keep translated files updated and offer an excellent user experience
With local executions and test

SELC-3242 Updated translations

---

src/lib/components/Footer/Footer.tsx
src/lib/locale/it.ts

change footer link label of privacy policy to Informativa privacy
Tested in local

[SELC-1712] feat: change footer link label of privacy policy

---

src/examples/TranslationTextExample.tsx
src/lib/utils/__tests__/productId2ProductTitle.test.ts
src/lib/utils/productId2ProductTitle.tsx

Created a method that return productTitle receiving productId
In order to have a function to use in case the information is not returned from API rest

[SELC-3936] feat: Created a method that return productTitle receiving productId

---

README.md
src/lib/model/JwtUser.ts
src/lib/utils/storage.ts

Added two new exportable utilities methods for storage managment: parseJwt and isExpiredToken
In order to make re-usable utilities methods and then use them via import and thus eliminate code in other repositories

[SELC-4521] feat: Added two new exportable utilities methods for storage managment: parseJwt and isExpiredToken

---

package.json
yarn.lock

updated library mui italia to latest version
Improvment of performance of rendering partyList in case of a user with over 4k parties
Tested locally

[SELC-4696] Feat: update library mui italia for partList performance improvements

---

README.md
src/lib/components/EndingPage.tsx

[SELC-5006] feat: Added onClick action for second button + updated README
Added onClick action for second button 
[SELC-5006]: https://pagopa.atlassian.net/browse/SELC-5006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5006] feat: Added onClick action for second button + updated README

---

src/lib/components/Footer/Footer.tsx

[SELC-5001] feat: Lang switch also based on lang query parameter
In order to change the language and the selection also when a language arrives in query parameter
[SELC-5001]: https://pagopa.atlassian.net/browse/SELC-5001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5001] feat: Lang switch also based on lang query parameter

---

src/lib/components/EndingPage.tsx

feat: homogeneous margin in paragraph element
In order to have a homogeneous distance between the elements

feat: homogeneous margin in paragraph element

---

src/lib/components/ErrorBoundary/components/__tests__/BlockingErrorPage.test.tsx
src/lib/components/tests/FilterModal.test.tsx
src/lib/utils/constants.ts

Add ADMIN_EA to  roleLabels function
add ADMIN_EA to pnpgRoleLabels functions
Updated USER_ROLE enum
To prepare to handle the new user_role
Tested locally

[SELC-5105-5104] Feat: update utility functions and add ADMIN_EA

---

package.json
src/lib/components/Toast.tsx
yarn.lock

changed responsive of the toast component
To change responsive of the add user notify component and update mui italia
Tested locally

[SELC-4584] Feat changed alert style and update mui italia library

---

README.md
package.json
src/lib/components/Toast.tsx
yarn.lock

[SELC-4584] Feat: changed alert style and update mui italia library

---

README.md

bump version

---

package.json
src/lib/components/Toast.tsx
yarn.lock

Revert "[SELC-4584] Feat changed alert style and update mui italia library"

---

package.json
src/lib/components/Toast.tsx
yarn.lock

update mui italia library version
Tested locally

[SELC-4594] Feat: update mui italia version

---

src/lib/utils/constants.ts

added Actions enum
To handle the new user permisions through actions and not by user role

[SELC-5259] feat: Created enum actions to handle user permissions

---

src/examples/redux/store.ts
src/lib/hooks/usePermissions.ts
src/lib/index.ts
src/lib/redux/slices/permissionsSlice.ts

Added user permissions hook
added user permissions slice 
In order to allow handling user permission with the actions

[SELC-5260] feat: userPermissions slice and hook

---

src/lib/utils/constants.ts

Added action UpdateInstitution 
To handle updating the name and email of institutions in pnpg.
Tested locally.

[SELC-5261] Feat: add action to update institution data

---

src/lib/config/env.ts

[SELC-5638] feat: Update "Accessibility" heading in footer
Replace the current link where you would be redirected (of the accessibility declaration for the year 2023/2024) with the link to the new declaration (2024/2025)
Tested that the new link redirect to the correct accessibility link
[SELC-5638]: https://pagopa.atlassian.net/browse/SELC-5638?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-5638] feat: Update "Accessibility" heading in footer

---

src/lib/components/SessionModal.tsx

lowered margin top for message prop
increased title fontSize 
adapt the style to figma Dialog design
Tested in local enviroment

[SELC-5650] Feat: Change sessionModal style for add notify

---

package.json
yarn.lock

add resolution for node-fetch to fix vulnerability
update react-scripts
By running application in local

[SELC-5937] Feat: Add resolution fix for node-fetch

---

package.json
src/lib/components/Footer/Footer.tsx
src/lib/locale/locale-utils.ts
yarn.lock

[SELC-6042] feat: Added language detection
In order to automatically detect the lang from browser.
An order has also been set, which include: querystring, sessionStorage, navigator
Tested in local environment: all the use case are satisfied
[SELC-6042]: https://pagopa.atlassian.net/browse/SELC-6042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SELC-6042] feat: Added language detection

---

src/lib/locale/locale-utils.ts

feat: Introduced support for region languages+save language into session storage
- Support region languages (es: EN-US, make the english as language portal
- Lang is stored in sessionStorage to make the choice valid as long as the session is valid
Tested by changing the web browser language to American English and other regional languages, all are detected correctly. The language is also saved only in the sessionStorage which allows it to be maintained in case of browser refresh and deleted in case the session expires

feat: Introduced support for region languages+save language into session storage

---

src/lib/utils/constants.ts

add user role ADMIN_EA_IO in UserRole type 
Add transaltion for user role label

[SELC-6375] feat: add new user role ADMIN_EA_IO

---

src/lib/utils/constants.ts

New action CreateDelegation 
To hide the add delegation button for users roles ADMIN_EA_IO.

[SELC-6381] feat: new action to handle create delegation

---

src/lib/config/env.ts

[SELC-6116] feat: update link accesability in common footer

---

src/lib/utils/api-utils.ts

Returned the status code to allow custom handling when the function is imported.

[SELC-6417] feat: return status code for 404 case

---

src/lib/utils/constants.ts

Remove admin ea io

---

src/lib/utils/api-utils.ts

Return promise with null value for status code 404

fix: return null for status code 404

---

package.json
src/lib/components/Toast.tsx
yarn.lock

update mui italia version to 1.5.3

---

package.json
src/lib/utils/constants.ts
yarn.lock

New action to handle the documents scetion visibility.

[SELC-6986] feat: and new action and update mui italia

---

src/lib/utils/api-utils.ts

Modify extractResponse function to handle list of codes
to handle status 200 and 201 for oidcExchange.

[SELC-7070] feat: handle list of success codes

---

src/lib/hooks/__tests__/useFocus.test.tsx
src/lib/hooks/useFocus.ts

- add hook useFocus
- add test useFocus
Added hook to handle focus of an element after page change
It was tested locally

[SELC-7243] feat: added hook useFocus to handle focus for accessibility

---

package.json
src/lib/utils/constants.ts
yarn.lock

Add new action ListProductGroups = 'Selc:ListProductGroups',
Handle visibility of groups section for EA

feat: add ListProductGroups action to Actions enum

---

package.json
yarn.lock

remove not used api-spec-converter

---

src/lib/decorators/__mocks__/withLogin.tsx
src/lib/hooks/useLogin.ts
src/lib/model/JwtUser.ts
src/lib/model/User.ts

refactor: make User and JwtUser fields optional and update mockedUser
